services:
  server:
    build: .
    networks:
      - traefik-proxy
      - default
    environment:
      ROOM_JWT_SECRET: ${ROOM_JWT_SECRET}
    labels:
      - traefik.enable=true
      - traefik.http.routers.auction.rule=Host(`auction.dk-gl.eu`)
      - traefik.http.routers.auction.entrypoints=https
      - traefik.http.services.auction-backend.loadbalancer.server.port=80
    restart: always
networks:
  traefik-proxy:
    external: true
    name: traefik-proxy
